### ISSUE TITLE
outdated angular-ui-router version

### ISSUE THREAD

**Issue by vmartynets** [auth0-samples/auth0-angularjs-samples#10]
(AUTH-4045)
Samples using outdated version of angular-ui-router (0.4.2 when up-to-date version is 1.0.3)

**Comment by TakesTheBiscuit** [comment]
The commit 084a3d9 seems to have broken things for me:
0.4.2 npm install works ok - but 1.0.3 seems to be failing something to do with a core conflict.

**Comment by vmartynets** [comment]
@TakesTheBiscuit what version of npm do you use?
