### ISSUE TITLE
Following quickstart and SPA sends an opaque token to backend

### ISSUE THREAD

**Issue by opyate** [auth0-samples/auth0-angularjs-samples#17]
I've asked the initial question here: https://github.com/auth0/angular-jwt/issues/157

I have 2 clients set up, one for the Angular 1 SPA, and one for the Python/Flask API. Both set to `HS256`.

When logging in via the hosted page, the callback to my SPA is in seemingly in the correct format:

    https://myapp.com/callback#access_token=NLcH4l337-d-8D7x&expires_in=7200&token_type=Bearer&state=g02VgjgHLGU.ZDFBEEF1S5Fj5El8ZI8X&id_token=abc.xyz.def

However, the SPA sends (what I'm told) an opaque token to my API:

    Authorization: Bearer NzmWR9AfD40PEYfC

Please let me know where in my travels I might have made the wrong turn. Thanks!

**Comment by opyate** [comment]
I simply have to change this line to get `id_token` from localStorage instead of the opaque `access_token`:
https://github.com/auth0-samples/auth0-angularjs-samples/blob/a28650bd2b6ce227f2ef73c5f9679c8bab1b4bb7/03-Calling-an-API/app/app.js#L65

**Comment by chenkie** [comment]
Reopening as switching to the ID token isn't the solution. You need to send the access token to your API and not the ID token.

There's likely a problem with how you have your API authorization configured. You need to get a JWT for your access token and not an opaque access token like you're getting now. Can you paste your `auth0.WebAuth` config here?

**Comment by opyate** [comment]
Hi Ryan, thanks for the reply. Here you go:

```
angularAuth0Provider.init({
      clientID: '6FYq0WqAS3ZHS5Zv9A8OSKD1eyWZDFTi',
      domain: 'mydomain.eu.auth0.com',
      responseType: 'token id_token',
      audience: 'https://api.mydomain.com',
      redirectUri: 'https://www.mydomain.com/callback',
      scope: 'openid profile email'
    });
```

(using a fake clientID for this issue)

**Comment by chenkie** [comment]
Thanks

Can you confirm that you've created your API in the [APIs section](https://manage.auth0.com/#/apis) of the dashboard and that its identifier is the URL you've got as your `audience` in your config above?

**Comment by opyate** [comment]
The `audience` is the API's ID. But...

It works now - perhaps it's support who made a change to my account or my random settings fiddling earlier propagated finally.

Thanks for looking into this.
