### ISSUE TITLE
No instructions for executing some parts on docker

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-angularjs-samples#37]
There should be a specified instruction for when the user executes the app through docker in order to properly configure the callback_url, this variable comes prepopulated when the sample's downloaded as:

http://localhost:3000/callback

but the app doesn't run by default in the localhost address, to find out the ip of the docker machine(running "docker-machine ip" on the command prompt will display the correct IP), the callback_url should match this IP in this way:

http://+docker-machine-ip+:3000/callback

**Comment by aaguiarz** [comment]
@alexisluque shouldn't localhost work?

**Comment by jimmyjames** [comment]
@rafanog if you follow the instructions in the `README` and run Docker with `sh exec.sh` (or `.\exec.ps1` if using Windows), it will launch Docker on localhost. If you continue to have this issue, please reopen or open a new issue with additional information about how you are launching Docker.
