### ISSUE TITLE
API calls doesn't work while executing on docker

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-angularjs-samples#38]
The API calls included in the Angular.js quickstart due to the difference in IP between the execution in localhost and on docker, the "API_URL" variable should be transfered to the .env file to centralize that configuration.

**Comment by jimmyjames** [comment]
Hi @rafanog, I'm going to close this issue as it's pretty old, and I was able to run the app and call an API using docker and following the instructions in the `README`. If this is still an issue, please reopen or create a new issue.
